const parseISO = require("date-fns").parseISO;
const format = require("date-fns").format;
const escpos = require("escpos");
// install escpos-usb adapter module manually
escpos.USB = require("escpos-usb");

function printReceipt(req) {
    let data = req;

    // Select the adapter based on your printer type
    const device = new escpos.USB();
    // const device  = new escpos.Network('localhost');
    // const device  = new escpos.Serial('/dev/usb/lp0');

    const options = { encoding: "UTF-8" /* default */, width: 63 };
    // encoding is optional

    const printer = new escpos.Printer(device, options);

    device.open(function () {
        printer
            .font("a")
            .align("ct")
            .style("b")
            .size(1, 1)
            .text(data.store.name);

        printer
            .style("")
            .size(0, 0)
            .text("------------------------------------------------");
        printer
            .font("b")
            .align("lt")
            .style("")
            .size(0, 0)
            .tableCustom([
                { text: data.store.name, align: "LEFT", width: 0.5 },
                {
                    text: format(new Date(), "dd-MM-Y hh:mm aaa"),
                    align: "RIGHT",
                    width: 0.5,
                },
            ])
            .tableCustom([
                {
                    text: `Address: ${data.store.address}`,
                    align: "LEFT",
                    width: 0.5,
                },
                {
                    text: "GENERATED BY: " + data.user.name,
                    align: "RIGHT",
                    width: 0.5,
                },
            ])

            .tableCustom([
                {
                    text: `Store Contact: ${data.store.phone}`,
                    align: "LEFT",
                    width: 0.5,
                },
                {
                    text: "Store Name: " + data.store.name,
                    align: "RIGHT",
                    width: 0.5,
                },
            ])

            .tableCustom([
                {
                    text: "Customer Contact: " + data.customer.phone,
                    align: "LEFT",
                    width: 0.5,
                },
                {
                    text: "GSTIN/UIN: " + data.store.gst,
                    align: "RIGHT",
                    width: 0.5,
                },
            ]);

        printer.drawLine();
        printer.tableCustom([
            { text: "ITEM", align: "LEFT", width: 0.25 },
            { text: "QTY", align: "LEFT", width: 0.25 },
            { text: "PRICE", align: "LEFT", width: 0.25 },
            { text: "NETVALUE", align: "RIGHT", width: 0.25 },
        ]);
        data.invoice[
            data.invoice.productList ? "productList" : "product"
        ].forEach((element, i) => {
            printer.tableCustom([
                {
                    text: data.product_names[i],
                    align: "LEFT",
                    width: 0.25,
                },
                {
                    text: element.quantity,
                    align: "LEFT",
                    width: 0.25,
                },
                {
                    text: element.selling_price,
                    align: "LEFT",
                    width: 0.25,
                },
                {
                    text: `Rs. ${
                        parseInt(element.selling_price) *
                        parseInt(element.quantity)
                    }`,
                    align: "RIGHT",
                    width: 0.25,
                },
            ]);
        });
        printer.drawLine();

        printer.tableCustom([
            { text: "SUB TOTAL", align: "LEFT", width: 0.5 },
            {
                text:
                    "Rs. " +
                    data.invoice[
                        data.invoice.subTotal ? "subTotal" : "subtotal"
                    ],
                align: "RIGHT",
                width: 0.5,
            },
        ]);
        if (parseInt(data.invoice.discount) > 0)
            printer.tableCustom([
                { text: "DISCOUNT", align: "LEFT", width: 0.5 },
                {
                    text: `Rs. ${data.invoice.discount}`,
                    align: "RIGHT",
                    width: 0.5,
                },
            ]);
        printer.tableCustom([
            { text: "TAX", align: "LEFT", width: 0.5 },
            {
                text:
                    "Rs. " +
                    data.invoice[
                        data.invoice.gstAmount ? "gstAmount" : "gst_amount"
                    ],
                align: "RIGHT",
                width: 0.5,
            },
        ]);
        printer.tableCustom([
            { text: "TOTAL PAYABLE", align: "LEFT", width: 0.5 },
            {
                text:
                    "Rs. " +
                    data.invoice[
                        data.invoice.amountPayable ? "amountPayable" : "payable"
                    ],
                align: "RIGHT",
                width: 0.5,
            },
        ]);

        printer.drawLine();

        printer
            .font("b")
            .align("ct")
            .size(0, 0)
            .text("THANK YOU FOR CHOOSING US");

        printer.font("a").align("ct").size(0, 0).text("Powered by oceanpos.in");

        printer
            .style("")
            .size(0, 0)
            .text("------------------------------------------------");

        printer.cut();
        printer.close();
    });
}

const express = require("express");
const bodyParser = require("body-parser");
const cors = require("cors");
const app = express();

const corsOptions = {
    origin: ["http://localhost:8080", "http://localhost:8000"],
};

app.use(bodyParser.json());
app.use(cors(corsOptions));
app.use(bodyParser.urlencoded({ extended: true }));

app.post("/print-receipt", cors(corsOptions), (req, res) => {
    printReceipt(req.body);

    res.sendStatus(204);
});

app.listen(3000, () => console.log("Print server is listening, port 3000"));
